### ISSUE TITLE
wiki per-site recaptcha keys

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/chef#10]
We currently use recaptcha on the wiki sites, but this leads to errors on non-wiki.openstreetmap.org sites. We should have per-site credential pairs via databags.

**Comment by tomhughes** [comment]
Done in https://github.com/openstreetmap/chef/commit/6d0cd3cd047cf2dc6d47d6482865d7aafe2588d2

**Comment by tomhughes** [comment]
Main wiki moved to data bag in https://github.com/openstreetmap/chef/commit/1ca376f593b53960f4963fce4892fe20f8c7e2dd

**Comment by tomhughes** [comment]
Foundation and board wiki fixed in https://github.com/openstreetmap/chef/commit/efa19e7783071a0ca31a742e3fc20163bbfc4975
