### ISSUE TITLE
Enable ToC limiting on wiki.osm.org

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/chef#107]
The Table of Contents section on some wiki pages is too long. As per the discussion at https://wiki.openstreetmap.org/wiki/Talk:Wiki#Limiting_TOCs there needs to be a change to the stylesheet so that the Template:TOC_limit is effective.

**Comment by gravitystorm** [comment]
I received this suggestion via email:

>You could fix that by adding the following lines to https://wiki.openstreetmap.org/wiki/MediaWiki:Common.css: 

```
/* Allow limiting of which header levels are shown in a TOC;
   <div class="toclimit-3">, for instance, will limit to
   showing ==headings== and ===headings=== but no further
   (as long as there are no =headings= on the page, which
   there shouldn't be according to the MoS). */
/* TemplateStyles */
.toclimit-2 .toclevel-1 ul,
.toclimit-3 .toclevel-2 ul,
.toclimit-4 .toclevel-3 ul,
.toclimit-5 .toclevel-4 ul,
.toclimit-6 .toclevel-5 ul,
.toclimit-7 .toclevel-6 ul {
	display: none;
}
```

**Comment by tomhughes** [comment]
I don't think that's managed by chef - it's effectively a wiki page that can be edited in the wiki by anybody with admin powers.

**Comment by tomhughes** [comment]
Is it just me, or is that TOC_Limit template not actually used anywhere?

**Comment by tomhughes** [comment]
I've added the CSS though I can't really test it as there don't seem to be any examples.
