### ISSUE TITLE
Cookbook testing

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/chef#13]
It's easier to contribute when you're confident that your PR won't fail spectacularly.

From experience elsewhere I can recommend the following:
- [Rubocop](https://github.com/bbatsov/rubocop) for linting the ruby code
- [Foodcritic](http://acrmp.github.io/foodcritic/) for checking for cookbook antipatterns
- [chefspec](https://github.com/sethvargo/chefspec) for testing logic in recipes without actually executing them
- [Test Kitchen](http://kitchen.ci/) for actually running the recipes in vms/containers

They all cover different aspects of the cookbooks so I'd suggest using all of them.

To start I'd suggest making rubocop and foodcritic config files to turn off things that we're currently relying on. Then would be to get test-kitchen working for various cookbooks.

**Comment by gravitystorm** [comment]
See #74 for test-kitchen.

**Comment by tas50** [comment]
This is a great list. I'd highly recommend Cookstyle over Rubocop though. Cookstyle is the wrapper of rules we use at Chef for our own cookbook development. It's better suited for cookbooks and generally allows you to avoid having a .rubocop.yml file at all.

https://github.com/chef/cookstyle

**Comment by gravitystorm** [comment]
I think we got the ball rolling with the cookbook testing, and although there's plenty of work still to do, there's no need to keep this issue open since it's a never-ending task.
