### ISSUE TITLE
Mapnik version problems

### ISSUE THREAD

**Issue by kocio-pl** [openstreetmap/chef#132]
Which version are we using currently on OSMF servers?

The problem is related to label placement bug in Mapnik. Sometimes it's rendered outside the polygon, so this important information is missing:

http://www.openstreetmap.org/#map=8/-1.060/32.750

However IOSB server using the same style shows them right:

https://tile.iosb.fraunhofer.de/#map=8/-1.060/32.750/3

@giggls says it's using Mapnik 3.0.12 package for Debian 9: 

https://packages.debian.org/source/stretch/mapnik

but I'm surprised, because the fix is not yet released and will be probably included in 3.0.16:

https://github.com/mapnik/mapnik/pull/3771#issuecomment-341449227

Could you test and deploy the version which uses correct labels placement?

**Comment by tomhughes** [comment]
We're using 3.0.9+ds-1 currently. As far as I know that's ab Ubuntu build, not a Debian one - in fact I just checked and it's the build that shipped with xenial.

If there's a newer Ubuntu build (released versions only please) that you'd like us to update to then just let me know the details.
