### ISSUE TITLE
change wgJobRunRate for wiki to value >0

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/chef#133]
I looked at https://github.com/openstreetmap/operations/issues/165 and I found https://www.mediawiki.org/wiki/Manual:Job_queue

As I understand this documentation, changing https://github.com/openstreetmap/chef/blob/680ff1ff298a48b923644ea32b3dea392fca299a/cookbooks/mediawiki/templates/default/LocalSettings.php.erb#L230 to nonzero value would fix problem of categories and "what links here" not working, but unfortunately it is not recommended

> If possible, it is recommended that you disable this default behaviour by setting $wgJobRunRate to 0

I proposing to do it because (1) I would be able to make PR that would implement this change (2) current situation of not processing jobs at all seems for me to be worse that doing what would work, but not in the recommended way.

For reference - it appears that running jobs is scheduled at https://github.com/openstreetmap/chef/blob/4670fb28130f0c5f6371ddc4932bf856725ee589/cookbooks/mediawiki/templates/default/mediawiki.cron.erb, but I have no idea why it is not working properly.

**Comment by matkoniecz** [comment]
Is it maybe possible to check logs why runJobs.php from https://github.com/openstreetmap/chef/blob/4670fb28130f0c5f6371ddc4932bf856725ee589/cookbooks/mediawiki/templates/default/mediawiki.cron.erb is not resulting in updates of category listings and "what links here" listings? (sorry if logs are available to public somewhere and I failed to find them)

**Comment by tomhughes** [comment]
As you noticed we run jobs from cron so it would not be correct to change that setting - you'll notice the documentation for that setting says it's for use if you're unable to run from the command line, and we can and do.

I've just verified that the cron job appears to be correct - I ran it manually and there were just a small number of jobs that ran, presumably those which had been scheduled since the last time cron ran it.

**Comment by matkoniecz** [comment]
> we run jobs from cron 

So what is not working and results in https://github.com/openstreetmap/operations/issues/165 ?

Is some configuration missing that would generate jobs for populating categories?

Is some special kind of jobs not configured to be run? Maybe refreshLinks.php also should be run from Cron?

**Comment by tomhughes** [comment]
I believe that is covered in some detail in the comments on that ticket - there are issues with mediawiki that need solving upstream.
