### ISSUE TITLE
update MediaWiki from 1.28 to 1.29.1

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/chef#134]
According to https://www.mediawiki.org/wiki/Manual:Installation_guide current stable is 1.29.1

Unfortunately in changelog I see no mention of fixing broken job handling, but maybe it is fixed anyway? Especially as https://phabricator.wikimedia.org/T168723 is mentioned as cherry picked for 1.29, despite not appearing on https://phabricator.wikimedia.org/source/mediawiki/browse/REL1_29/RELEASE-NOTES-1.29

1.28 update chef commit: https://github.com/openstreetmap/chef/commit/a9fa15ee42760a1c6073d01547dd8907b202d65b

**Comment by tomhughes** [comment]
Updated in 176d46fe9b5deb4080f433b1ca7f7786492fda9a.

**Comment by matkoniecz** [comment]
Thanks!
