### ISSUE TITLE
New version for donate.openstreetmap.org

### ISSUE THREAD

**Issue by nebulon42** [openstreetmap/chef#142]
There would be a new version for rollout on donate.openstreetmap.org, see https://github.com/osmfoundation/donation-drive/pull/12.

Not sure if this is the right place to report that, please advice better places otherwise.

**Comment by tomhughes** [comment]
As far as I can see we already deploy updates from the repository automatically.

**Comment by tomhughes** [comment]
Indeed it looks like those changes are live?

**Comment by nebulon42** [comment]
Hm, they weren't when I looked despite the PR being merged already some time ago. Interesting. Thanks.
