### ISSUE TITLE
Don't redirect server-status on frontends

### ISSUE THREAD

**Issue by zerebubuth** [openstreetmap/chef#144]
While doing something completely different, I noticed that some of [the munin API graphs](https://munin.openstreetmap.org/openstreetmap/www.openstreetmap/api_waits_www.html) have been dead since early January:

![image](https://user-images.githubusercontent.com/271360/35221873-c98170d8-ff73-11e7-9396-95b0e934f8bd.png)

Running `munin-run` on `spike-01` gives:

```
/usr/lib/ruby/2.3.0/open-uri.rb:225:in `open_loop': redirection forbidden: http://spike-01/server-status -> https://www.openstreetmap.org/server-status (RuntimeError)
	from /usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:35:in `open'
	from /etc/munin/plugins/api_waits_spike-01:9:in `uri_and_times_from_status'
	from /etc/munin/plugins/api_waits_spike-01:55:in `<main>'
```

As does `curl`:

```
matt@spike-01:/etc/munin/plugins$ curl http://localhost/server-status
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.openstreetmap.org/server-status">here</a>.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at localhost Port 80</address>
</body></html>
```

Do we need to whitelist requests to `/server-status` from `localhost` before the [catch-all redirect](https://github.com/openstreetmap/chef/blob/783fe0218688c7af51f4493c76b4a1c22213486a/cookbooks/web/templates/default/apache.frontend.erb#L298)?

**Comment by tomhughes** [comment]
Why would this have started redirecting? We haven't actually forced redirection on the main site yet!

**Comment by tomhughes** [comment]
Ah it was c249fadcc5ce27698d1f11fe5ec4a1c299786b3c which changed the wildcard vhost to redirect to https rather than http.
