### ISSUE TITLE
Rendering problems with osm-carto v4.7.0

### ISSUE THREAD

**Issue by kocio-pl** [openstreetmap/chef#147]
There are some strange rendering artifacts (![screen shot 2018-01-29 at 20 43 35](https://user-images.githubusercontent.com/14875493/35531252-b64006c4-0536-11e8-902a-31ea3b539ae9.png)) on different POIs, reported after deploying osm-carto v4.7.0 (however no changes in the style code was made). 

Examples:
https://www.openstreetmap.org/node/5141331468
https://www.openstreetmap.org/node/5148254822
https://www.openstreetmap.org/node/5370583084
https://www.openstreetmap.org/node/4693394595

see also https://github.com/gravitystorm/openstreetmap-carto/issues/3043 for screenshots.

Reported rendering server is orm (I'm not aware of any other than this).

**Comment by tomhughes** [comment]
What does this have to do with us? Style issues need to be reported at the style repository.

**Comment by tomhughes** [comment]
To put it another way, the only thing we changed was the style sheet, and rendering is not something anybody here knows anything about.

**Comment by tomhughes** [comment]
Well one machine seems to have a toilet icon for that first one while the other just have a blob:

* scorch: ![scorch](http://scorch.openstreetmap.org/19/272233/185647.png)
* orm: ![orm](http://orm.openstreetmap.org/19/272233/185647.png)
* yevaud: ![yevaud](http://yevaud.openstreetmap.org/19/272233/185647.png)
* vial: ![vial](http://vial.openstreetmap.org/19/272233/185647.png)

**Comment by tomhughes** [comment]
So scorch (the only one with the icon) is the only one that hasn't rendered with the updated style. So it seems to be a style issue to me.

**Comment by kocio-pl** [comment]
I'm surprised, but it really looks like a style problem on my rendering test... Thanks for checking it up!

**Comment by gravitystorm** [comment]
Confirmed as a style issue in https://github.com/gravitystorm/openstreetmap-carto/issues/3043
