### ISSUE TITLE
Disable MobileFrontend at OSMF wiki

### ISSUE THREAD

**Issue by nebulon42** [openstreetmap/chef#159]
I'd like to disable the MobileFrontend extension at OSMF wiki while keeping it active at the OSM wiki. The reason is that the new OSMF wiki theme is responsive and so the dedicated mobile frontend should not being displayed.

With my limited knowledge of Chef I figured out that all the extensions live in inc.php files that are somehow all included in the LocalConfig. How would we specify which extensions we want to have enabled? Write a list and only include those in the list in the LocalConfig?

Ref https://github.com/osmfoundation/osmf-mediawiki-skin/issues/9

**Comment by tomhughes** [comment]
Just remove it from the common extensions and only include it in the wikis that need it.

**Comment by tomhughes** [comment]
Broadly speaking, yes. Though note that there are four wikis in total (main, osmf, board and dwg).

**Comment by nebulon42** [comment]
Ah, thanks for the hint.

**Comment by nebulon42** [comment]
When visiting osmfoundation.org with my phone I still saw the dedicated mobile page. https://wiki.osmfoundation.org/wiki/Special:Version also still mentions the extension. @tomhughes Do you have an idea why that might be?

**Comment by tomhughes** [comment]
Not really. I amended your commit to force removal of the extension so it should be gone.

**Comment by tomhughes** [comment]
Hopefully 4ebef80a5ec6e33572be1b35ff89b142aa3afb09 will have fixed it.

**Comment by nebulon42** [comment]
Yes, that did it. Thanks!
