### ISSUE TITLE
git-core package no longer exists on Ubunutu 18.04

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/chef#180]
Installing the git cookbook fails on a freshly installed Ubuntu 18.04 because it cannot find the Debian package 'git-core'. Looks like it is just 'git' now.

**Comment by tomhughes** [comment]
I fixed that in 6eb04cacfcf5d156bbc30ed9d0be0e79de6685ec surely?

**Comment by lonvia** [comment]
ups, forgot to rebase. Sorry for the noise.
