### ISSUE TITLE
Low zoom rendering frequency

### ISSUE THREAD

**Issue by kocio-pl** [openstreetmap/chef#184]
Do you think it's possible to make low zoom re-rendering more often, like once a week rather than 1-2 times every month?

We use now new, less forgiving algorithm for multipolygons and they can be more easily broken during editing, which is visible on rendering. There were notable problems lately with biggest lakes in America, Africa and Asia, which just disappeared from default layer (on low zoom) for few weeks.

There is enough computation power to do this without even dropping tiles in the Saturday nights for example:

https://munin.openstreetmap.org/openstreetmap.org/render.openstreetmap.org/renderd_processed.html

**Comment by kocio-pl** [comment]
Hi, I wonder do you think about this idea?

**Comment by jeisenbe** [comment]
We've had another request from this in relation to disappearing country labels when multipolygons are broken.

**Comment by jidanni** [comment]
Folks, there are less tiles to update at lower zoom levels, and more reason to do so:
As with #3725, the media might come up with crazy stories:
- "OSM takes revenge for being banned in China!"
- "Hacker wipes the name of the world's most populous country off the map"

**Comment by jeisenbe** [comment]
It would be good to know if there are technical limitations that might be solvable. 

If the low zoom tiles are too intensive on server resources, we (at [gravitystorm/openstreetmap-carto]( https://github.com/gravitystorm/openstreetmap-carto)) could improve the rendering for z1 to z6 at by using the reduced complexity water polygons and coastlines for these zoom levels. 

I believe that rendering large lakes takes up the most server resources at z1 to z3, where few other features are shown, and the water bodies and oceans are still a significant portion for z5 to z7 (although the landcover and some other features are also present).

**Comment by jidanni** [comment]
In fact all you need to do is rerender that trouble spot (middle of
China) at those two zoom levels... what's that? Four tiles perhaps?

**Comment by jidanni** [comment]
And in the future, to avert similar news media panics ("They stole the
name of New York City again") there should be a button, available to the
OSM commander(s) in chief, to refresh (draw a rectangle on map) an
arbitrary area, at the given zoom levels, with no further ado.

**Comment by jidanni** [comment]
In fact, all you need is, the Chief's browser. Only used for emergency purposes. Whenever the chief uses his Chief's browser, all the tiles he browses get updated immediately, benefiting everybody. That way the chief, could just zoom into some trouble area, confirm that it now looks good, and case closed.

This Chief's browser, could be defined by a regular browser sending a special cookie, or special user-agent.

No need to be burdened by wasteful updates of tons of irrelevant other tiles.

**Comment by HolgerJeromin** [comment]
@jidanni 
Are you doing the coding stuff needed for that "chief's browser"? 
Which BTW probably does not really work as rendering the low zoom needs many hours.

**Comment by jidanni** [comment]
I'm just saying please put these two tiles
3) http://tools.geofabrik.de/map/#3/7.0510/148.5039&type=Geofabrik_Standard&grid=1
![Q_1](https://user-images.githubusercontent.com/1230959/55158022-ddd34480-5198-11e9-8ae5-0d0ea770ac7b.jpg)
and 4) http://tools.geofabrik.de/map/#4/22.3848/122.0927&type=Geofabrik_Standard&grid=1
![Q_2](https://user-images.githubusercontent.com/1230959/55158039-ed528d80-5198-11e9-962e-5260cbf78a2b.jpg)
in front of the list of tiles your are currently processing. Thanks.
