### ISSUE TITLE
Any objection to shipping the fail2ban resources in the chef fail2ban cookbook

### ISSUE THREAD

**Issue by tas50** [openstreetmap/chef#190]
I'm curious if the authors of the fail2ban resources would object to including those resources in the official fail2ban cookbook that Chef maintains. I'd like to put some work into our current attribute driven cookbook and these resources seem nicely thought out / implemented.

**Comment by tomhughes** [comment]
No objection from me - take what you want!

**Comment by Firefishy** [comment]
@tas50 We're a small volunteer team which runs the infrastructure for OpenStreetMap project. We're always looking for help ;-)
