### ISSUE TITLE
Run rails job workers for openstreetmap-website

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/chef#201]
In https://github.com/openstreetmap/openstreetmap-website/pull/2037 we're setting up a rails job system. This needs workers running in production to actually process the jobs queue.

The standard way of doing so is with `bundle exec rake jobs:work`. This is just a simple daemon, so if it crashes, something needs to be monitoring it to restart it, start it on boot, etc

I don't know what the preferences are here with this kind of thing (systemd/upstart/whatever), so I'm opening a ticket initially rather than providing a patch.

**Comment by gravitystorm** [comment]
If you want to go one extra level of indirection, a common way to handle this in the Rails world is using a Procfile, which describes what processes need to be run for a given app. Procfiles were originally invented by Heroku - see https://devcenter.heroku.com/articles/procfile . An example would include e.g.

```
worker: bundle exec rake jobs:work
```
Then we could use https://github.com/ddollar/foreman to export the Procfile into whichever format (systemd, upstart, inittab) is preferred. 

The only advantages of the Procfile+foreman approach is future proofing, in case the openstreetmap-website codebase ends up with multiple types of worker (I'm not sure how likely that is) or if you want to make the chef recipes app-agnostic, e.g. to run different rails applications which might have their own Procfiles.

I'm fairly ambivalent about this, but if the Procfile approach is preferred then I can do that too. I thought it worth explaining here anyway.

**Comment by tomhughes** [comment]
I don't seem to have `jobs:work` in my rake tasks? Is there something that needs to be configured first?

**Comment by mmd-osm** [comment]
I believe you need to merge the changes in https://github.com/openstreetmap/openstreetmap-website/pull/2037/files (gravitystorm:delayed_job) into your local test branch for `jobs:work` to appear.
