### ISSUE TITLE
Wiki module editing broke

### ISSUE THREAD

**Issue by nyurik** [openstreetmap/chef#216]
I am not sure if https://github.com/openstreetmap/chef/commit/ceab552534e0b204ce2eecd05584603d0ad23cfc is the reason, but Lua module editing has stopped working.  To reproduce -- go to any module page, e.g. https://wiki.openstreetmap.org/wiki/Module:Sandbox/yurik and click edit. Expected a custom lua editor with a debug console. Instead, it shows a regular text editor.  Once saved, the module still works, but having no lua debugger makes it much harder to develop, plus it requires every change to be saved before it can be seen if it is working or not.  CC: @Tigerfell

**Comment by tomhughes** [comment]
It's working for me.

**Comment by nyurik** [comment]
I found the reason, and I suspect this to be some sort of a visual editor bug -- I somehow ended up with the `VEE=wikitext` cookie being set, and after deleting it, it began working for me too.
