### ISSUE TITLE
wiki.osm.org: install Skin Minerva_Neue

### ISSUE THREAD

**Issue by saerdnaer** [openstreetmap/chef#226]
The mobile view on wiki.osm.org is currently broken. Installing https://www.mediawiki.org/wiki/Skin:Minerva_Neue might fix that.

**Comment by tomhughes** [comment]
Well rather than randomly installing a different should we not find out what the problem is and fix it? or at least make an informed decision to change skin after know why the current one isn't working and that the proposed new one will resole that.

**Comment by saerdnaer** [comment]
As listed on https://www.mediawiki.org/wiki/Extension:MobileFrontend#Setup_a_skin 

> The following skins are compatible with MobileFrontend:
> 
> Skin:Minerva Neue (stable, default on WMF wikis)
> Skin:Vector (default desktop skin, uses an experimental responsive mode for mobile)
> Skin:Timeless (experimental skin)

I would opt for the new, stable default WMF skin stead of debugging why the the experimental mobile part of vector does not work.

**Comment by tomhughes** [comment]
So that is certainly useful information and makes a reasonable argument.

Do we know what wikimedia and/or wikipedia are using?

**Comment by saerdnaer** [comment]
WMF is the Wikimedia Foundation and thereby *.wikipedia.org, compare https://en.wikipedia.org/wiki/Special:Version

**Comment by saerdnaer** [comment]
Looks like the fix was successful – after clicking the "Mobile View" link at the bottom of a wiki page, I now get the responsive version:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/40266/54482629-e8134b80-4846-11e9-8e63-8286ab63b0b3.png">

Mobile phones (at least my Android and iOS test devices) automatically select the mobile version.
