### ISSUE TITLE
Enable syntax highlighting on the wiki

### ISSUE THREAD

**Issue by picsi** [openstreetmap/chef#231]
Basically, this extension: https://www.mediawiki.org/wiki/Extension:CodeMirror

It makes editing, particularly templates, a much more pleasant experience.

**Comment by tomhughes** [comment]
I think we already have some sort of syntax highlighting extension enabled so I'd like to hear from the wiki admins before considering this.

**Comment by tomhughes** [comment]
I think https://www.mediawiki.org/wiki/Extension:CodeEditor is what I was thinking of. In any case any request for a new extension is really something that should go via the wiki admins.

**Comment by Tigerfell** [comment]
We do have both extensions enabled (see https://wiki.openstreetmap.org/wiki/Special:Version). Someone proposed it in the wiki as well (https://wiki.openstreetmap.org/wiki/Talk:Wiki#Bring_syntax_highlighting_to_this_wiki.21), but it is not clear which extension is meant.

**Comment by picsi** [comment]
That was me on the wiki :)

I linked to the incorrect extension in my first post here, I've since corrected it. It's this one: https://www.mediawiki.org/wiki/Extension:CodeMirror

**Comment by Firefishy** [comment]
@Tigerfell could you advise on the correct solution here?

**Comment by Tigerfell** [comment]
I think we can add it. It is used in Wikimedia projects and it seems to be switched off by default. All users interested in syntax highlighting can switch it on individually, but the user experience for the majority would not change. Additionally, no one opposed the addition when mentioned at Talk:Wiki.

**Comment by Tigerfell** [comment]
@Firefishy Should I open a PR?

**Comment by Firefishy** [comment]
@Tigerfell yes, that would be awesome. Appreciate it.
