### ISSUE TITLE
Stopping Fast Scrapes from spamming Diaries

### ISSUE THREAD

**Issue by seb-1204** [openstreetmap/chef#237]
As proposed [here](https://www.openstreetmap.org/user/alexkemp/diary/275003), can the admin team please introduce the suggestions or start a constructive discussion about the suggestion to start limiting the amount of spam on the diaries.

This is an example of the relevant section when utilised (by default it is set to provide code to stop FTP, etc. dictionary attacks & would need to be modified to stop hi-speed HTTP(S) attacks):

```
# Stop Dictionary Attacks:
# This stops NEW connection rates exceeding 3/minute per IP
# (in addition, a 60 sec quiet period then required)
# The ports used need to be identical in all 4 lines below
# See: https://www.frozentux.net/iptables-tutorial/iptables-tutorial.html#RECENTMATCH
$IPT -A INPUT -p TCP -m tcp -m multiport --destination-ports 20,21,25,110,143 \
     -m state --state NEW -m recent --update \
     --seconds 60 --hitcount 4 --rttl -j DROP
$IPT -A INPUT -p TCP -m tcp -m multiport --destination-ports 20,21,25,110,143 \
     -m state --state NEW -m recent --update \
     --seconds 60 --hitcount 3 --rttl -j LOG \
    --log-prefix "Dictionary attack: "
$IPT -A INPUT -p TCP -m tcp -m multiport --destination-ports 20,21,25,110,143 \
     -m state --state NEW -m recent --update \
     --seconds 60 --hitcount 3 --rttl -j DROP
$IPT -A INPUT -p TCP -m tcp -m multiport --destination-ports 20,21,25,110,143 \
     -m state --state NEW -m recent --set

# Route the rest to the appropriate user chain
$IPT -A INPUT -p TCP -i $INET_IFACE -j tcp_inbound
$IPT -A INPUT -p UDP -i $INET_IFACE -j udp_inbound
$IPT -A INPUT -p ICMP -i $INET_IFACE -j icmp_packets
```

**Comment by tomhughes** [comment]
I have explained why IP blocks are no use in this case.

**Comment by gravitystorm** [comment]
For the benefit of other people reading this thread, the spam problem is coming from a distributed botnet. Therefore each IP is only used a small number of times, on average around 3 times. Limiting the number of requests from an IP will therefore have little, if any, effect on the problem, while affecting many hundreds of legitimate users behind [Carrier-grade NAT](https://en.wikipedia.org/wiki/Carrier-grade_NAT).
