### ISSUE TITLE
Tiles in London need to be forced out of cache

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/chef#244]
I'm not sure where best to put this ticket, but the OSM website Mapnik tiles need a serious flush in London:

![Screen Shot 2019-08-04 at 14 44 45](https://user-images.githubusercontent.com/361423/62424436-62454f00-b6c6-11e9-8aae-12b2a9901ed2.png)

This is presumably related to the problem noted at:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-August/023327.html
https://lists.openstreetmap.org/pipermail/talk-gb/2019-August/023329.html

Also noticed on Twitter:
https://twitter.com/MatthewMarks42/status/1157965326736404481

**Comment by tomhughes** [comment]
No they don't anymore that they needed forcing into cache. They will get dirtied as the reverts happen and will then rerender naturally just as the broken version rerendered naturally.

It's a moot point anyway because we have no tooling to it.
