### ISSUE TITLE
Tilecache nginx loop possible

### ISSUE THREAD

**Issue by danfai** [openstreetmap/chef#292]
With the current configuration of backup server in upstream there is the possibility to get more than one hop away to different tile caches.
Because of the round robin nature the servers can access each other in loops (when squid is down or overloaded in all involved hosts). In a small test using 4 nodes, 2 active squid and all running nginx I got up to 9 hops.

There are multiple ways to fix this:
1.  Either implement some logic in nginx to limit the number of hops.
2. Or let nginx directly talk to the other squid instances.

This issue might be of low importance because it is unlikely to happen with most squids online. But in case of overloaded nodes, the problem might become worse. Monitoring the requests on the map, I saw at most 3 hops for now.

I can work on a fix, but wanted to discuss this first.

**Comment by tomhughes** [comment]
Sorry I'm confused... What map are you talking about exactly? There's no map of cache peers as far as I know, and we got rid of most peering anyway?

**Comment by danfai** [comment]
The tilecaches at cookbooks/tilecache/templates/default/nginx_tile.conf.erb: upstream tile_cache_backend
I meant requests on the official map osm.org, sorry.

**Comment by tomhughes** [comment]
So the nginx caches are talking to each other, not just to the local squid? Is that intended @Firefishy?

**Comment by danfai** [comment]
I mean it is a good idea to have them as backups, which works fine (primarily local squid, and when the local squid is not running other tilecache nginx).
The problem only starts when there are more than one squid down.

**Comment by Firefishy** [comment]
Yes, it is intended, but far from optimal at the moment. Best would be to select a smaller pool of backup "peers" to fallback on.

**Comment by Firefishy** [comment]
I have a PR nearly ready which runs a regular cron peer test from each cache to all other caches. With those results I could then create a better tree of peers to use per cache.

**Comment by tomhughes** [comment]
@danfai well it shouldn't really be possible that nginx is running and not squid in normal operation - that would be very much a rare error case of some sort.

**Comment by danfai** [comment]
Looking forward to that PR. Wanted to suggest some weights depending on the latency to the hosts as well, but will check in later :)

**Comment by danfai** [comment]
> @danfai well it shouldn't really be possible that nginx is running and not squid in normal operation - that would be very much a rare error case of some sort.

Yeah it should be unlikely, but I was also surprised as I got one tile over multiple tilecaches and a render server "far away" (I think it was South America or Australia, when I am sitting in Germany).
Of course there is more than one thing, which leads to such behavior.

**Comment by Firefishy** [comment]
No longer an issue with Fastly.
