### ISSUE TITLE
Generalise Nominatim recipe

### ISSUE THREAD

**Issue by mvl22** [openstreetmap/chef#32]
The chef script which installs Nominatim currently has hard-coded URLs and a few other parameters:
https://github.com/openstreetmap/chef/blob/master/cookbooks/nominatim/recipes/base.rb

It would be excellent if this could be generalised so that someone wanting to install their own Nominatim could set the relevant values for their installation (e.g. domain name) and then run the recipe.

We currently have a bash script for installing our Nominatim:
https://github.com/cyclestreets/nominatim-install/blob/master/run.sh
but if a standard chef recipe were available we would probably be able to deprecate that.

**Comment by tomhughes** [comment]
Our chef scripts are not really designed to be reusable by anybody else, in the same way that we don't reuse any of the community cookbooks but instead write our own from scratch that do things "the way we want".

That's not to say I wouldn't take a PR to do this, but it's not something I'm likely to spend time on myself unless we ever found ourselves wanting to run multiple instances.

**Comment by Firefishy** [comment]
Closing due to age. Nominatim installation options have moved on significantly.
