### ISSUE TITLE
*-latest.torrent redirections do not work correctly (not updating to latest torrents)

### ISSUE THREAD

**Issue by mnalis** [openstreetmap/chef#371]
As mentioned in [closed PR 451](https://github.com/openstreetmap/operations/issues/451#issuecomment-743421149) (so I don't know if it will be seen, hence this ticket), HTTP `301 redirect` correctly updates HTTP redirect target for `*-latest.osm.bz2` and `*-latest.osm.pbf` and other data files,  **but not** for `*-latest.*.torrent` files.

Example of failing to redirect to new torrent file (_after more than 20 hours after the new torrent files became available_) (timezone CET):
```
% wget -O /dev/null https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf.torrent
--2020-12-12 17:00:46--  https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf.torrent
Resolving planet.openstreetmap.org (planet.openstreetmap.org)... 130.117.76.10, 2001:978:2:2c::172:a
Connecting to planet.openstreetmap.org (planet.openstreetmap.org)|130.117.76.10|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://planet.openstreetmap.org/pbf/planet-201130.osm.pbf.torrent [following]
--2020-12-12 17:00:46--  https://planet.openstreetmap.org/pbf/planet-201130.osm.pbf.torrent
Reusing existing connection to planet.openstreetmap.org:443.
HTTP request sent, awaiting response... 200 OK
Length: 281206 (275K) [application/x-bittorrent]
Saving to: ‘/dev/null’
```

while at the same time wget of  `planet-latest.osm.pbf` redirects OK (and it worked even before it started redirecting to  `ftp5.gwdg.de` mirror):
```wget -O /dev/null https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
--2020-12-12 17:09:39--  https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
Resolving planet.openstreetmap.org (planet.openstreetmap.org)... 130.117.76.10, 2001:978:2:2c::172:a
Connecting to planet.openstreetmap.org (planet.openstreetmap.org)|130.117.76.10|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://planet.openstreetmap.org/pbf/planet-201207.osm.pbf [following]
--2020-12-12 17:09:40--  https://planet.openstreetmap.org/pbf/planet-201207.osm.pbf
Reusing existing connection to planet.openstreetmap.org:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/pbf/planet-201207.osm.pbf [following]
--2020-12-12 17:09:40--  https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/pbf/planet-201207.osm.pbf
Resolving ftp5.gwdg.de (ftp5.gwdg.de)... 134.76.12.6, 2001:638:60f:110::1:2
Connecting to ftp5.gwdg.de (ftp5.gwdg.de)|134.76.12.6|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58831508921 (55G) [application/octet-stream]
```

**Comment by zorun** [comment]
It's not just the redirection, it seems that the symlinks were not updated: ihttps://planet.openstreetmap.org/pbf/

`planet-201207.osm.pbf.torrent` was correctly created on 2020-12-11, but `planet-latest.osm.pbf.torrent` is still from 2020-12-04.

**Comment by Firefishy** [comment]
I think there was a race condition, the script creating the planet files [was modified with the new changes](https://github.com/openstreetmap/chef/commit/f84ac307449ea2d9ef5ba89eb71c53ee9c9fcfc8) after it was already running. I have manually updated the symlinks.

Hopefully all work on ~18th Dec 2020 and then we can close this ticket.

**Comment by mnalis** [comment]
Yes, `planet-latest.osm.pbf.torrent` redirecting to `planet-201214.osm.pbf.torrent` (and others) seem to have been generated OK now. Closing.
