### ISSUE TITLE
Generate RSS/Atom feed for .torrent files?

### ISSUE THREAD

**Issue by mnalis** [openstreetmap/chef#373]
PR #359 implemented generation of `.torrent` files and RSS feed for them. Part which generates `.torrent` files was implemented (via PR #360), but RSS part was not implemented at that time.

RSS feed is useful to automatically create healthy bittorrent swarm when new torrents are released. Process is often called [Broadcatching](https://en.wikipedia.org/wiki/Broadcatching), and many [clients easily support it](https://en.wikipedia.org/wiki/Comparison_of_BitTorrent_clients#Features_II). Without RSS, people willing to help spread the network load must either manually watch and add new torrents every Friday (which gets boring fast), or they must be technically inclined to write automation scripts - which results in less participation, and thus smaller and slower swarms.

I've written original RSS implementation and (and hopefully addressed @pnorman concerns about generating XML in shell script in [this comment](https://github.com/openstreetmap/chef/pull/359#discussion_r528416672)). However, I can rewrite RSS support in perl (or, perhaps, python) using XML modules if that is preferred to simple shell function approach.

I'd like to know if such PR is likely to be accepted before I invest time to write it (or if not, reasons for RSS not being wanted would be helpful).

**Comment by Firefishy** [comment]
I think there should be RSS feeds for all types of files (.pbf, .osm.bz2, .torrent etc). Shell script is likely ok [using xmlstarlet](https://stackoverflow.com/questions/12827343/linux-send-stdout-of-command-to-an-rss-feed), but not echo pipe. Updates should be validated (xmllint) before it goes live.

**Comment by mnalis** [comment]
Thanks for info!

I'll have a go at it that way, then. I was thinking of separate RSS for each file type keeping last 5 .torrent entries (so  `/pbf/planet-latest.osm.pbf.torrent.xml` RSS feed would have entries for last 5 `/pbf/planet-XXXXXX.osm.pbf.torrent` files, etc. for each of 6 data dumps we create torrents for. Then torrent clients could subscribe to wanted RSS feeds and automatically join the swarm when such torrents are published, sharing the network load.

While RSS referencing raw (big) data dump files is also possible, IMHO it would be counterproductive, as it would _increase network load_ on `planet.openstreetmap.org` instead of _helping reduce it_ by building up torrent swarm. Anyway I'll write a easy function so it will be easy to extend it any way required.

**Comment by Firefishy** [comment]
I would say go for a simpler XML filename.

**Comment by ldeffenb** [comment]
Being one of the folks that have been watching the RSS feed and automatically downloading and seeding planet data, I'll vote for this one!  As soon as the RSS feed URL is available, I'll add it to my Synology Download Station and auto-seed each new release.

**Comment by mnalis** [comment]
RSS for torrents is implemented in PR https://github.com/openstreetmap/chef/pull/383

Lacking entire OSM system, I've tested locally, and it seems to work fine. 
Let me know if changes are required or pull it if it is good to go. Cheers!

**Comment by mnalis** [comment]
Hi @Firefishy,

I was wondering if you had time to look at this PR for RSS on torrent files? I've implemented it using `xmlstarlet` and verified via `xmllint`, as you indicated you would prefer. 

I completely understand that you've probably been busy elsewhere, but I'm just checking if this issue might had fallen through the cracks and out of your attention (it's been finished for several weeks with no comments from sysadmins).

**Comment by ldeffenb** [comment]
Are we ever going to get an RSS feed for the planetary .torrent files?  I would love to auto-download and seed each planet PBF as it appears, but really don't like the idea of directly scraping the URLs to watch for a new one to appear...

**Comment by hbogner** [comment]
I would like to see torrent rss too. Already seeding from planet.osm-hr.org but geting new torrents in a dirty way, rss would be cleaner way to do it, and to do it via rss plugin on some desktop machines.

**Comment by Firefishy** [comment]
Change is live.
RSS feeds:
https://planet.openstreetmap.org/pbf/planet-pbf-rss.xml
https://planet.openstreetmap.org/pbf/full-history/history-pbf-rss.xml
https://planet.openstreetmap.org/planet/planet-bz2-rss.xml
https://planet.openstreetmap.org/planet/full-history/history-bz2-rss.xml
https://planet.openstreetmap.org/planet/changesets-bz2-rss.xml
https://planet.openstreetmap.org/planet/discussions-bz2-rss.xml

**Comment by mnalis** [comment]
I'm getting reports there is a bug... While valid XML, it seems that many RSS readers detect it as having no entries. That is because all `<item>`s should be **inside** `<channel>`, and not after it. I'm looking into it.

**Comment by Firefishy** [comment]
> I'm getting reports there is a bug... While valid XML, it seems that many RSS readers detect it as having no entries. That is because all `<item>`s should be **inside** `<channel>`, and not after it. I'm looking into it.

My RSS reader (theoldreader.com) was able to.load the feeds with issue, but I guess they may have a relaxed parser.

Would you mind opening a separate ticket for this?

**Comment by Firefishy** [comment]
I've manually patched the feeds for the moment. It would be good to get this fixed ASAP.

**Comment by mnalis** [comment]
@Firefishy I've created a pull request https://github.com/openstreetmap/chef/pull/417 that fixes it in code

**Comment by mnalis** [comment]
@ldeffenb and everybody interested, RSS feeds are not implemented and now documented in [wiki](https://wiki.openstreetmap.org/wiki/Planet.osm#BitTorrent_RSS.2FAtom_feed)

**Comment by ldeffenb** [comment]
Thank you for the ping!  I tried to load it earlier, but my Synology was reporting that there was nothing in the feed.  I now see that this is fixed and can confirm that my Synology Download Stations is happy with the new feed and will be automatically adding planets as they appear.
