### ISSUE TITLE
Kitchen: local testing

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/chef#394]
One of the goals of https://www.openstreetmap.org/user/migurski/diary/391942 was to enable local testing of a cookbook:

_"For people who would like to change the configuration of wiki.openstreetmap.org a working cookbook would make it easier to test locally with test-kitchen and offer contributions that are known to work prior to deployment."_

I don't see how we're taking full advantage of test kitchen already. Ideally, we would see the build complete successfully and then be able to log on to the wiki to make sure everything looks ok. 

 `kitchen converge wiki`  builds a Docker container that includes a wiki with all relevant extensions enabled. However, I cannot access the container from the outside, as no ports are being exposed. So I started exposing some ports in .kitchen.yml:

```
  - name: wiki
    driver:
       hostname: wiki.demo
       ports:
          - '0.0.0.0:443:443'
          - '0.0.0.0:8084:80'   
```

The point I'm struggling with is that I cannot set a custom hostname (like "wiki.demo"), and using the default wiki.openstreetmap.org collides with the productive wiki instance. Also security settings inside the container make testing quite difficult.

How would you go about testing those cookbooks locally that includes logging in to a Wiki using a browser? Was that even part of the original plan?

//cc: @migurski

**Comment by tomhughes** [comment]
Well it's for testing, not for deploying a development environment - that's not what test kitchen is for.

The tests don't generally represent our production environments anyway because they test at the recipe level, without any of the configuration our roles would normally apply to a particular service.

**Comment by mmd-osm** [comment]
I didn't have a development environment in mind, but rather inspecting build results in a browser. I found something similar to the example above in the kitchen-dokken repo (as https://github.com/test-kitchen/kitchen-dokken/blob/master/kitchen.yml#L73-L83), that's why assumed this is a valid use case.

The wiki cookbook appeared to be sufficiently self-contained to give this a try, even though test-kitchen can only simulate a tiny bit of the environment with mostly fake data.

**Comment by tomhughes** [comment]
I've no idea if it's possible to tell test kitchen to export ports from it's docker containers because as I say that's not really it's purpose...
