### ISSUE TITLE
Use tilelog to generate tile logs

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/chef#401]
I wrote [tilelog](https://github.com/openstreetmap/tilelog) to generate the [tile log files](https://planet.openstreetmap.org/tile_logs/) from the Fastly logs instead of the current system which generates from the unused squid cache nodes.

It's written in python and uploaded to pypi, so it can be installed with 

```
python3 -m venv venv
. venv/bin/activate
pip install --upgrade tilelog
```

Usage is `tilelog --date 2021-03-23` and then it will generate a file called `tiles-2021-03-23.txt.xz` If `--date` is omitted, it will calculate what yesterday was in UTC and generate that file. 

Optional parameters are --staging and --region which specify the AWS s3 location for Athena results and the Athena region.

AWS access needs to be set up, either with [environment variables](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables) or `~/.aws/config`

If there's anything I can do to help like additional command-line options or defaults, let me know.

A known issue is that [it takes longer than it should to run](https://github.com/openstreetmap/tilelog/issues/1)

ref https://github.com/openstreetmap/operations/issues/485

**Comment by Komzpa** [comment]
Hello, what can we do to get this deployed faster?

**Comment by Lokks** [comment]
Hello @pnorman !  Is there any news about deploying tilelog to prod?

**Comment by pnorman** [comment]
Any news will be posted here. If you want to help get this deployed, a PR would be the best way.

**Comment by tomhughes** [comment]
Apparently I missed this request. I'll have a look...
