### ISSUE TITLE
RSS feed does not work in all RSS readers

### ISSUE THREAD

**Issue by mnalis** [openstreetmap/chef#416]
As mentioned in https://github.com/openstreetmap/chef/issues/373, `<item>`s should be inside `<channel>` tag to be proper RSS, otherwise some readers see empty RSS feed (although XML itself is valid).

Also [W3 feed validator](https://validator.w3.org/feed/) complains about `<comment>` and `<enclosure length=`

**Comment by mnalis** [comment]
Here is PR which fixes the bug (and few other smaller ones that W3 RSS validator reported)

**Comment by mnalis** [comment]
should be fixed with PR https://github.com/openstreetmap/chef/pull/417

**Comment by mnalis** [comment]
The XMLs should probably be removed / regenerated, in order to get all required attributes at correct places.

**Comment by Firefishy** [comment]
All regenerated and published. Quick check they all validate correctly now.

**Comment by Firefishy** [comment]
Tweeted: https://twitter.com/OSM_Tech/status/1396888552290590722

**Comment by ldeffenb** [comment]
> All regenerated and published. Quick check they all validate correctly now.

I'll confirm that my Synology Download Station reported the feed as empty a few hours ago, but now it properly found the planet files and added them automatically.  Great job to all involved!
