### ISSUE TITLE
Postgres server started before all configuration available

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/chef#42]
For setting up the nominatim DB slave, I have to remove the data in postgres' data dir including server.crt/.key and recovery.conf. It would be nice to be able to recover these files with chef after the base backup is done. However, starting chef at this point goes horribly wrong because chef starts up the postgres server before these files are copied back, generally destroying the database replica in the process. 

Anything we can do about this?

**Comment by tomhughes** [comment]
I normally just stop chef while I do a basebackup, then start it again afterwards. It's been a while since I did it but I'm pretty sure that always worked for me. I know that I'm always quite careful though.

**Comment by lonvia** [comment]
I thought I had it working once like this so I wouldn't exclude that this problem has been introduced with newer chef versions.

Looking into the code, might the solution be as simple as moving [the service definition](https://github.com/openstreetmap/chef/blob/master/cookbooks/postgresql/recipes/default.rb#L22) for postgres to the end of that file?

**Comment by tomhughes** [comment]
I don't *think* that will cause any problems... I think the current ordering is a result of it originally being written when you couldn't do forward references to resources. I'll try it...
