### ISSUE TITLE
Would you be intressted in a free Teleport Pro account?

### ISSUE THREAD

**Issue by benarent** [openstreetmap/chef#420]
Hi OpenStreetMap Team.

We ( Teleport ) have recently launched a campaign to help strengthen open source projects. Since OSM has a large infrastructure, It seems like it would be good fit. It'll make access easier and provide an audit log for all activity on hosts. I've written up how the Tinkerbell projects uses Teleport here. https://goteleport.com/blog/securing-oss-infrastructure/ 

Let me know if you are interested in the cloud version or I can also help get you setup with a version you can run.

Thanks for providing an awesome project.

**Comment by Firefishy** [comment]
@benarent I appreciate the offer, but we are OK for the moment. If we change our mind we will contact you ;-)
