### ISSUE TITLE
Install R v4.1.2 and Redis v6 on dev server

### ISSUE THREAD

**Issue by gregrs-uk** [openstreetmap/chef#541]
Many thanks for migrating everything over to the new dev server. Would it please be possible to install R version 4.1.2 and Redis v6? These are needed for [FHODOT](https://gregrs.dev.openstreetmap.org/fhodot/). I would've created a pull request for [this file](https://github.com/openstreetmap/chef/blob/master/cookbooks/dev/recipes/default.rb) but I'm not sure of the syntax. Thanks.

**Comment by tomhughes** [comment]
Were they installed on the old server? I mean if they're packaged then I can install them but I can't guarantee particular versions like that.

**Comment by tomhughes** [comment]
In particular it would be helpful to know the package name for R because I can't exactly search for it!

**Comment by gregrs-uk** [comment]
Thanks @tomhughes. Those were the versions installed on the old server. If those versions aren't possible then I'm sure the latest packaged versions will be fine. It looks like the package for R is `r-base`.

**Comment by gregrs-uk** [comment]
Ah sorry, see you've already fixed this in https://github.com/openstreetmap/chef/commit/6111b5c99c2494be0aa22be75f15a9dbcbecca14. Thanks
