### ISSUE TITLE
downloading populated_places not needed anymore for the tiles

### ISSUE THREAD

**Issue by HolgerJeromin** [openstreetmap/chef#58]
I am quite sure, that after
https://github.com/gravitystorm/openstreetmap-carto/pull/1461 
downloading ne_10m_populated_places.zip is not [needed anymore](https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.yaml)
But it is still downloaded:
https://github.com/openstreetmap/chef/blob/650d2449041e1e3a14845bf2c33e71172bae5d0f/roles/tile.rb#L65-L70
This change is live since a few month.
@gravitystorm can you confirm this?

**Comment by gravitystorm** [comment]
Yes, the file is no longer needed. The processing code for it can also be removed: see https://github.com/openstreetmap/chef/blob/650d2449041e1e3a14845bf2c33e71172bae5d0f/cookbooks/tile/recipes/default.rb#L191-L204

@HolgerJeromin do you fancy making a pull request for this?

**Comment by HolgerJeromin** [comment]
I dont think i have time and enough knowledge for this, sorry. :-)
