### ISSUE TITLE
Clarify or close the private chef repo

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/chef#61]
There's a private OSMF Chef repository with various roles and/or cookbooks, for hysterical raisins. I don't have any access to this so I'm not sure about the details.

I'm interested in knowing if we can shut this down yet? I assume there are still cookbooks or roles in there with secrets hard-coded, or are there other reasons why some aspects can't be made public? Is there any other reasons to the private repo?

**Comment by tomhughes** [comment]
The only things in there now are the data bags containing the various password, private keys,etc. The last remaining roles were moved out a couple of months ago and there haven't been any cookbooks there for 18 months.

**Comment by gravitystorm** [comment]
Super, thanks for the info.
