### ISSUE TITLE
Use openstreetmap.style config file for tileservers

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/chef#64]
We've noticed that the tileservers use the default .style file from osm2pgsql when processing updates (by not specifying one, it defaults to the default.style)

https://github.com/openstreetmap/chef/blob/master/cookbooks/tile/templates/default/replicate.erb#L69-L74

The openstreetmap-carto project includes a style file for use with osm2pgsql. This ensures that the database layout matches what the stylesheets expect, as well as allowing use of arbitrary osm2pgsql versions instead of forcing people to upgrade to the latest if columns get changed.

I believe there's no substantial differences between the master version in osm2pgsql and that in the latest openstreetmap-carto release, so this is not currently a major issue. But it might be worth changing the update script (and the import script, if there is one).

**Comment by tomhughes** [comment]
So you're right that there are no differences, or rather all the differences are in comment lines.

The problem we have is that although we only have one layer at the moment the cookbook is designed to support have multiple layers with different styles, but only one database to support them, which means there is no obvious way to decide which style's style file to use.

**Comment by pnorman** [comment]
> cookbook is designed to support have multiple layers with different styles, but only one database to support them

This **will** break with 3.0 of OpenStreetMap Carto. Well, it would if not for the fact that we're not using the functionality.

**Comment by kocio-pl** [comment]
Isn't this issue resolved, now that we have osm-carto v4.0.0 deployed already?

**Comment by pnorman** [comment]
Resolved with 02f9c7c
