### ISSUE TITLE
Doesn't work https://planet.openstreetmap.org/

### ISSUE THREAD

**Issue by F-15023** [openstreetmap/chef#719]
After 15 december the site https://planet.openstreetmap.org/ does not respond. Connection timeout. 
All mirrors haven't updates since 15 december.
Maybe this commit broke something:
https://github.com/openstreetmap/chef/commit/bed594905942640a53812e404335213395cdec16

**Comment by tomhughes** [comment]
See https://community.openstreetmap.org/t/openstreetmap-org-currently-offline-operations-team-are-working-to-restore-15-december-2024/122930.
