### ISSUE TITLE
Decouple munin_plugin from munin service definition

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/chef#80]
Many cookbooks use the `munin_plugin` provider, but this has a compile-time dependency on the `service[munin-node]` declaration. This makes it hard to test cookbooks (e.g. squid) independently.

The basic workaround is to add "include_recipe[munin::default]" to every cookbook that uses the `munin_plugin` resource. But that's not ideal since it slows down all the tests (and squid doesn't actually depend on munin being installed) and feels a bit icky.

Instead it would be better to allow cookbooks to call `munin_plugin` without having the whole of `munin::default` pulled in too. This could be achieved by inverting the notification, i.e. make `service[munin]` subscribe to the munin_plugin, but that's not straightforward due to the restart_munin attribute, and also subscribing to a particular munin_plugin invocation.

I propose using a dummy resource, to decouple the munin_plugin notifications from the service[munin] subscriptions, something like:

change the after_created in munin/resources/plugin.rb:
```
def after_created
  notifies :run , "execute[plugin-requires-munin-restart]" if restart_munin
end
```
somewhere:
```
# This is a dummy resource for other resources to subscribe to
execute 'plugin-requires-munin-restart' do
  command 'date'
  action :nothing
end
```
in munin/recipes/default.rb:
```
service[munin] do
   [...]
   subscribes :run, "execute[plugin-requires-munin-restart", :delayed
end
```

Thoughts? Is there an easier way to decouple the plugins from the service definition?

**Comment by tomhughes** [comment]
Is "I want to vomit" a valid thought?

Our cookbooks are built on an assumption that the munin recipe is applied to every node, because it is.

I'm not even clear how this is supposed to work, and it seems you aren't either as you don't seem to know where the dummy resource should go. The obvious place is, of course, the `munin::default` recipe, but wouldn't that completely defeat the object of the whole thing? But where else could it (reasonably) go?

What is the actual goal here? To be able to use `munin_plugin` without running the `munin::default` recipe? Will that not make the test artificial in that it won't be testing how the things are actually used?

Or is there a genuine dependency bug here in that we shouldn't using `munin_plugin` without including the recipe?

**Comment by zerebubuth** [comment]
> Is "I want to vomit" a valid thought?

Sure, although it's not very helpful.

I think the goal here is to try to be able to test each cookbook independently (as much as possible) from the others. Having tests means that people, including me, are more confident that any changes we're making or proposing aren't going to have catastrophic effects if/when they're applied.

Testing is, of course, not a silver bullet. But it can be an important part of screening for errors before they're live.

**Comment by tomhughes** [comment]
My problem is that I'm not convinced testing cookbooks on their own is a hugely meaningful thing to do and it's also going to be a huge amount of work to decouple them and we'll wind up with a lot of extra logic that only exists to allow that decoupled testing.

**Comment by zerebubuth** [comment]
@gravitystorm and I were discussing this the other day, and there's definitely different layers to testing, including but probably not limited to:

1. Does it do what it was told it to do (i.e: files written, packages installed, correct strings in config files)
2. Does it do what it was _intended_ it to do (i.e: not block all browsers from getting tiles)

And cookbook testing is definitely stronger on the former than the latter. Some kind of integration tests may be the way to go for the latter, although I'm not sure what that looks like at the moment.

Personally, I think putting some work into giving some sort of safety net is worthwhile. At present, I find it hard to navigate the Chef recipes, and often resort to `ack`ing the whole tree to find where stuff is being set / pulled in from.

I think it's analogous to a suite of unit tests on a large codebase: It's more work to write code in a testable manner, but that usually also makes it more regular, readable and helps n00bs such as myself avoid the foot-gun.

**Comment by lonvia** [comment]
I think the decoupling of cookbooks is absolutely necessary to get us away from the 'development on production machines' mode. It is insane that I have to find the typos in my code by committing and deploying it on a machine that serves life traffic. test-kitchen, even without tests, would solve at least that issue.

**Comment by tomhughes** [comment]
Well it'll find the typos sure, but not the bigger issues - for that you want to be able to test "does the nominatim role apply without errors" which will catch typos and also larger cross-cookbook interactions.

So sure it's not bad to test individual cookbooks or recipes, I just worry it will be a lot of work to make it happen and to keep it working.

**Comment by gravitystorm** [comment]
> Or is there a genuine dependency bug here in that we shouldn't using munin_plugin without including the recipe?

I think there's a genuine dependency bug. It should be possible to call a cookbook resource (e.g. munin_plugin) without having to remember to also run a recipe first (e.g. munin::default). If the recipe is 100% required to be run, then the provider should take care of that. If it's not 100% necessary, then you should be able to call the provider without doing other things first.

In this case, I don't think it makes sense to make service[munin] a hard dependency of squid. I do think it's reasonable (although again debatable) to say that configuring squid's munin plugins is something the squid recipe should do.

The "somewhere" was just because I haven't tested where works so I didn't want to be wrong and cause confusion. I think munin/providers/plugin.rb would be suitable, perhaps within the two action blocks.

> Will that not make the test artificial in that it won't be testing how the things are actually used?

That's a reasonable question. I don't think it applies, since we can test that squid installs itself and configures the relevant munin plugins, and we can also write separate tests for the munin_plugin provider within the munin cookbook. And if we make these changes, then what we're testing will also be how things are actually used.

**Comment by tomhughes** [comment]
You can't put it in `munin/providers/plugin.rb` because (a) it will get duplicated for each plugin and (b) the service won't be able to subscribe to it because it won't be visible.

Every resource inside an LWRP is invisible to resources outside it and you can't subscribe/notify across that boundary, which is why we do the `after_created` stunt in the first place because that runs in the parent context, not in the nested context of the LWRP.

**Comment by gravitystorm** [comment]
Thanks @tomhughes !
