### ISSUE TITLE
Set a default for nameserver attributes?

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/chef#81]
https://github.com/openstreetmap/chef/blob/420bef370d088997cc4228451941e05e37c4e181/cookbooks/networking/templates/default/resolv.conf.erb#L5-L7

```
<% node[:networking][:nameservers].each do |nameserver| -%>
nameserver <%= nameserver %>
<% end -%>
```

This means that by default, any recipe that depends on `networking` gets no nameservers and generally fails on the first attempt to apt-get. This makes testing the cookbooks tedious since you need to explicitly set nameserver attributes for any cookbook that has networking::default somewhere in its dependencies.

There are (at least) a couple of options:

* Default to something sensible (e.g. 8.8.8.8) if no nameservers are specified. I'm not sure what the downsides of this would be though.
* Unpick the dependencies so that e.g. munin::default doesn't depend on networking::default.

**Comment by tomhughes** [comment]
Surely this is the least of the problems?

I mean it's just not valid to run the `networking::default` recipe without providing he necessary attributes to define the network and that includes a lot more than just the resolvers?

The networking recipe is a bit odd mind in that not everything is applied "live" and a lot of changes only take affect after the new reboot.

To be honest I'm not sure why `munin::default` includes `networking::default` anyway? I suspect it may have been me thinking I needed to do that to have the `firewall_rule` definition available? When in reality I suspect depending on the cookbook in metadata.rb is enough?

**Comment by tomhughes** [comment]
So I went with a slightly different option and stopped it trying to create `resolv.conf` if there are no nameservers - that turns out to be better because it means you get the local DHCP provided ones which means local names that are not in the public DNS can be resolved, like the name of my web proxy.
