### ISSUE TITLE
Can't install the correct version of squid on xenial

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/chef#84]
Our squid cookbook depends on squid 2.7, but that's no longer available in Ubuntu so we package our own version in a PPA:

https://launchpad.net/~osmadmins/+archive/ubuntu/ppa/+packages

The package claims to replace "squid3" which I guess is how the `package "squid"` part of the recipe is supposed to work. However, I can't get it to install on a xenial image. I've got a WIP test-kitchen config at https://github.com/gravitystorm/chef/commit/40da20e811bc0d7be7ade2af2c81648125986641 . When it runs, it install squid 3.5.12 . Uninstalling, apt-get update, reinstalling leads to the same place. I can only get it working by uninstalling squid, then running:

`sudo apt-get install squid=2.7.STABLE9-4ubuntu10 squid-common=2.7.STABLE9-4ubuntu10`

Can anyone shine a light onto this problem? What steps need to be taken to get the correct version of squid installed?

**Comment by tomhughes** [comment]
Squid has to be manually installed and pinned on tile cache servers.

**Comment by zerebubuth** [comment]
Would https://github.com/gravitystorm/chef/pull/1 help with pinning the version, so that it doesn't have to be done manually?

**Comment by tomhughes** [comment]
Maybe. I mostly haven't worried too much because @firefishy is supposed to be replacing the squid based implementation with a varnish based one ;-)

**Comment by zerebubuth** [comment]
Squid isn't the only thing that we install from PPA - does it make sense to move a "prefer osmadmins PPA" rule into the main apt recipe?

Although for that to work, we'd have to figure out why `apt-cache policy` isn't showing the `o=LP-PPA-...` origin which allows us to distinguish one PPA from another.

**Comment by mmd-osm** [comment]
We're running on _bionic_ and _squid 4_ these days. 

Can we close this issue?

**Comment by tomhughes** [comment]
Well I think at the moment our (patched) squid 4 is newer than the Ubuntu one so probably.
