### ISSUE TITLE
Improve tile cache logging

### ISSUE THREAD

**Issue by tomhughes** [openstreetmap/chef#94]
The request logging we do on the tile caches has a number of problems and could do with some improvement.

Each request is actually logged two, or sometimes three times, which is wasteful of I/O time and disk space on the caches. On top of which the logs that we recover to our central store are missing some important details.

The logs we currently generate are:
- `squid/access.log` standard squid access log with no UA or referer
- `squid/zere.log` added for @zerebubuth's analysis stuff has UA but no referer and is recovered to ironbelly
- `nginx/access.log` for https requests only and generally more detailed than squid logs with the UA and referer included

I would like to change the squid access log to include the UA and referer and whatever else @zerebubuth needs and drop the special zere log and potentially drop the nginx logs as well so long as it passes through the real IP and squid can be made to log that.

**Comment by zerebubuth** [comment]
Sounds good to me. Just let me know the new log format so that I can update the tile statistics tool.

**Comment by tomhughes** [comment]
@zerebubuth Is there a reason why `zere.log` logs the etag header from the response - does the tile statistics tool use that?
